# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [2]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date  None
2  Charlie      35     2022/03/01  88.0
3    David     NaN            NaN  92.5
4      NaN      40  April 5, 2022

### 🧯 2. Detecting Missing or Broken Values

In [3]:
df.isnull()

    Name    Age  Signup Date  Score
0  False  False        False  False
1  False  False        False   True
2  False  False        False  False
3  False   True         True  False
4   True  False        False  False

In [4]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
dtype: int64

In [6]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score
1    Bob  thirty     not a date  None
3  David     NaN            NaN  92.5
4    NaN      40  April 5, 2022

### 🧹 3. Cleaning Strategy Options

In [7]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0
})

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date   0.0
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5
4  Unknown      40  April 5, 2022

In [9]:
df.dropna()

      Name Age Signup Date Score
0    Alice  25  2022-01-01  95.5
2  Charlie  35  2022/03/01  88.0

### 🧬 4. Data Type Fixes

In [10]:
df.dtypes

Name              str
Age            object
Signup Date       str
Score          object
dtype: object

In [11]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                      str
Age                   float64
Signup Date    datetime64[us]
Score                 float64
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [12]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

/tmp/ipykernel_1880/1713118361.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(df["Age"].median(), inplace=True)
/tmp/ipykernel_1880/1713118361.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Score"].fillna(df["Score"].mean(), inplace=True)

0    95.5
1    92.0
2    88.0
3    92.5
4    92.0
Name: Score, dtype: float64

In [13]:
df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

/tmp/ipykernel_1880/3000949103.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

0   2022-01-01
1   2022-01-01
2   2022-01-01
3   2022-01-01
4   2022-01-01
Name: Signup Date, dtype: datetime64[us]

In [14]:
df["Name"].fillna("Unknown", inplace=True)

/tmp/ipykernel_1880/626038248.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Name"].fillna("Unknown", inplace=True)

0      Alice
1        Bob
2    Charlie
3      David
4    Unknown
Name: Name, dtype: str

### 🤓 6. Cleaned Data Review

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         4 non-null      str
 1   Age          3 non-null      float64
 2   Signup Date  1 non-null      datetime64[us]
 3   Score        3 non-null      float64
dtypes: datetime64[us](1), float64(2), str(1)
memory usage: 292.0 bytes

In [16]:
df.describe(include="all")

         Name        Age          Signup Date      Score
count       4   3.000000                    1   3.000000
unique      4        NaN                  NaN        NaN
top     Alice        NaN                  NaN        NaN
freq        1        NaN                  NaN        NaN
mean      NaN  33.333333  2022-01-01 00:00:00  92.000000
min       NaN  25.000000  2022-01-01 00:00:00  88.000000
25%       NaN  30.000000  2022-01-01 00:00:00  90.250000
50%       NaN  35.000000  2022-01-01 00:00:00  92.500000
75%       NaN  37.500000  2022-01-01 00:00:00  94.000000
max       NaN  40.000000  2022-01-01 00:00:00  95.500000
std       NaN   7.637626                  NaN   3.774917

🧪 Try It Yourself
Modify the data dictionary at the top of this notebook. Add:

A new column with some None and "" values

At least one row with all columns filled incorrectly Then re-run the notebook and fix it step-by-step.

In [21]:
myData = {
    "Name": ["Alice", "Bob", "Charlie", "David", None, None],
    "Age": ["25", "thirty", 35, np.nan, "40", None],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022", None],
    "Score": [95.5, None, 88.0, 92.5, "", None],
    "Height": [None, None, None, None, None, None]
}

md = pd.DataFrame(myData)
md
md.isnull()
md.isnull().sum()
md[md.isnull().any(axis=1)]

md.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0,
    "Height": -1
})

md.dropna()

md.dtypes

md["Age"] = pd.to_numeric(md["Age"], errors="coerce")
md["Score"] = pd.to_numeric(md["Score"], errors="coerce")
md["Signup Date"] = pd.to_datetime(md["Signup Date"], errors="coerce")
md["Height"] = pd.to_numeric(md["Height"], errors="coerce")
md.dtypes

md["Age"].fillna(md["Age"].median(), inplace=True)
md["Score"].fillna(md["Score"].mean(), inplace=True)

md["Signup Date"].fillna(md["Signup Date"].min(), inplace=True)

md["Name"].fillna("Unknown", inplace=True)
md["Height"].fillna(md["Height"].median(), inplace=True)

md.info()

df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         4 non-null      str
 1   Age          3 non-null      float64
 2   Signup Date  1 non-null      datetime64[us]
 3   Score        3 non-null      float64
 4   Height       0 non-null      float64
dtypes: datetime64[us](1), float64(3), str(1)
memory usage: 372.0 bytes

/tmp/ipykernel_59512/362123959.py:33: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  md["Age"].fillna(md["Age"].median(), inplace=True)
/tmp/ipykernel_59512/362123959.py:34: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  md["Score"].fillna(md["Score"].mean(), inplace=True)
/tmp/ipykernel_59512/362123959.py:36: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  md["Signup Date"].fillna(md["Signup Date"].min(), inplace=True)
/tmp/ipykernel_59512/362123959.py:38: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  md["Name"].fillna("Unknown", inplace=True)
/tmp/ipykernel_59512/362123959.py:39: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  md["Height"].fillna(md["Height"].median(), inplace=True)

         Name Age Signup Date  Score
count       4   4           4    4.0
unique      4   4           4    4.0
top     Alice  25  2022-01-01   95.5
freq        1   1           1    1.0

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

In [40]:
myDataframe = pd.read_csv("../../data/survey.csv")
myDataframe[myDataframe.isnull().any(axis=1)]
myDataframe.isnull().sum()

myDataframe.fillna
({
    "age": -1,
    "gender": "fm",
    "major": "none",
    "gpa": 1.1,
    "study_hours_per_week": -1,
    "satisfaction_1_5": 0,
    "survey_date": "2010-01-01",
    "dorm_resident": False,
    "expected_grad_year": "none",
    "income_range": "none",  
    "commute_minutes": -1,
    "clubs_member": False,     
    "attendance_rate": -1,
    "favorite_language": "yhiddish", 
    "comments": "none"   

})

myDataframe.dropna()

myDataframe["age"] = pd.to_numeric(myDataframe["age"], errors="coerce")
myDataframe["major"] = pd.to_numeric(myDataframe["major"], errors="coerce")
myDataframe["clubs_member"] = pd.to_datetime(myDataframe["clubs_member"], errors="coerce")

myDataframe.info()
myDataframe.describe()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            120 non-null    str
 1   age                   80 non-null     float64
 2   gender                97 non-null     str
 3   major                 0 non-null      float64
 4   gpa                   76 non-null     str
 5   study_hours_per_week  78 non-null     str
 6   satisfaction_1_5      74 non-null     str
 7   survey_date           88 non-null     str
 8   dorm_resident         87 non-null     str
 9   expected_grad_year    87 non-null     str
 10  income_range          99 non-null     str
 11  commute_minutes       67 non-null     str
 12  clubs_member          0 non-null      datetime64[s]
 13  attendance_rate       41 non-null     str
 14  favorite_language     101 non-null    str
 15  comments              68 non-null     str
dtypes: datetime64[s](1), float64(2), str(13)
memory usage: 15.1 KB

/tmp/ipykernel_1880/1309017940.py:29: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  myDataframe["clubs_member"] = pd.to_datetime(myDataframe["clubs_member"], errors="coerce")

             age  major clubs_member
count  80.000000    0.0            0
mean   21.237500    NaN          NaT
min    18.000000    NaN          NaT
25%    19.000000    NaN          NaT
50%    21.000000    NaN          NaT
75%    23.000000    NaN          NaT
max    25.000000    NaN          NaT
std     2.312562    NaN          NaN

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |