# 📊 04 - Data Input and Output

Most of data science is about **loading data, exploring it, and saving results**.  
In this notebook you will learn:
- Reading CSV files with Pandas
- Inspecting DataFrames (`head`, `info`, `describe`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [3]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""
with open("students.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("students.csv")
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

✅ **Your Turn**: Create your own small CSV (3–5 rows) and read it into Pandas.

In [4]:
work = """Name,Age,Position
Nate,22,cook
juan,20,pack
Rosario,21,pack
Yenna,20,pack
"""

with open("work.csv", "w") as f:
    f.write(work)

file = pd.read_csv("work.csv")
file

      Name  Age Position
0     Nate   22     cook
1     juan   20     pack
2  Rosario   21     pack
3    Yenna   20     pack

## 2. Exploring DataFrames

In [5]:
# Look at the first rows
df.head()

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

In [6]:
# Info about columns and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [7]:
# Summary statistics
df.describe()

             Age  Score
count   3.000000    3.0
mean   23.333333   90.0
std     1.527525    5.0
min    22.000000   85.0
25%    22.500000   87.5
50%    23.000000   90.0
75%    24.000000   92.5
max    25.000000   95.0

✅ **Your Turn**: Use `.head()` to preview your dataset and `.describe()` to see basic statistics.

In [ ]:
# file.head()

file.describe()

             Age
count   4.000000
mean   20.750000
std     0.957427
min    20.000000
25%    20.000000
50%    20.500000
75%    21.250000
max    22.000000

## 3. Writing CSV Files

In [ ]:
# Save the DataFrame to a new CSV
df.to_csv("students_copy.csv", index=False)
%ls *.csv

✅ **Your Turn**: Save your DataFrame to a CSV file called `my_data.csv`.

In [13]:
file.to_csv("coworkers.csv", index=False)
%ls *.cvs

ls: cannot access '*.cvs': No such file or directory

## 4. Reading Excel Files

In [ ]:
# Optional: Requires 'openpyxl' installed
# Save to Excel
df.to_excel("students.xlsx", index=False)

# Read Excel file
pd.read_excel("students.xlsx")

✅ **Your Turn**: Try saving your dataset to Excel and reading it back (if supported in your environment).

---
### Summary
- `pd.read_csv` loads data into a DataFrame.
- Use `.head()`, `.info()`, `.describe()` to explore quickly.
- `df.to_csv` and `df.to_excel` save results.
- Pandas makes file I/O simple and reliable.